version: 2

sources:
  - name: spotify
    database: polar-scene-465223-f7
    schema: "dp_lake_{{ target.name }}"
    tables:
      - name: staging_spotify_raw
      - name: bronze__spotify_recently_played_clean
        description: Table bronze nettoyée et dédupliquée par played_at + track_id