version: 2

sources:
  - name: spotify
    database: polar-scene-465223-f7
    schema: "{{ 'dp_lake_' ~ target.name }}"  # Jinja actif
    description: "Spotify data from universal JSON ingestion - similar to Garmin architecture"
    tables:
      - name: lake_spotify__stg_spotify_raw
        description: "Universal staging table for all Spotify data types with JSON schema (consistent with Garmin naming)"
        columns:
          - name: raw_data
            description: "Complete original record stored as JSON"
          - name: data_type
            description: "Type of Spotify data (recently_played, saved_tracks, saved_albums, playlists, top_artists, top_tracks, followed_artists)"
          - name: dp_inserted_at
            description: "Data platform insertion timestamp"
          - name: source_file
            description: "Original source file name"

models:
  - name: lake_spotify__svc_recently_played
    description: "Service layer - Recently played tracks with extracted key fields and JSON structures"
    columns:
      - name: played_at
        description: "Timestamp when track was played"
      - name: track_id
        description: "Spotify track ID"
      - name: track
        description: "Complete track information as JSON"
      - name: context
        description: "Playback context as JSON (playlist, album, etc.)"
        
  - name: lake_spotify__svc_saved_tracks
    description: "Service layer - Saved tracks with extracted key fields"
    columns:
      - name: added_at
        description: "Timestamp when track was saved"
      - name: track_id
        description: "Spotify track ID"
      - name: track
        description: "Complete track information as JSON"
        
  - name: lake_spotify__svc_saved_albums
    description: "Service layer - Saved albums with extracted key fields"
    columns:
      - name: added_at
        description: "Timestamp when album was saved"
      - name: album_id
        description: "Spotify album ID"
      - name: album
        description: "Complete album information as JSON"
        
  - name: lake_spotify__svc_playlists
    description: "Service layer - User playlists with extracted key fields"
    columns:
      - name: playlist_id
        description: "Spotify playlist ID"
      - name: playlist_name
        description: "Playlist name"
      - name: is_public
        description: "Whether playlist is public"
      - name: is_collaborative
        description: "Whether playlist is collaborative"
        
  - name: lake_spotify__svc_top_artists
    description: "Service layer - Top artists with extracted key fields"
    columns:
      - name: artist_id
        description: "Spotify artist ID"
      - name: artist_name
        description: "Artist name"
      - name: popularity
        description: "Artist popularity score"
      - name: genres
        description: "Artist genres as array"
        
  - name: lake_spotify__svc_top_tracks
    description: "Service layer - Top tracks with extracted key fields"
    columns:
      - name: track_id
        description: "Spotify track ID"
      - name: track_name
        description: "Track name"
      - name: popularity
        description: "Track popularity score"
      - name: duration_ms
        description: "Track duration in milliseconds"
      - name: explicit
        description: "Whether track has explicit content"
