version: 2

sources:
  - name: spotify
    database: polar-scene-465223-f7
    schema: "{{ 'dp_lake_' ~ target.name }}"  # Jinja actif
    description: "Spotify data from universal JSON ingestion - similar to Garmin architecture"
    tables:
      - name: lake_spotify__stg_spotify_raw
        description: "Universal staging table for all Spotify data types with JSON schema (consistent with Garmin naming)"
        columns:
          - name: raw_data
            description: "Complete original record stored as JSON"
          - name: data_type
            description: "Type of Spotify data (recently_played, saved_tracks, saved_albums, playlists, top_artists, top_tracks, followed_artists)"
          - name: dp_inserted_at
            description: "Data platform insertion timestamp"
          - name: source_file
            description: "Original source file name"

models:
  - name: lake_spotify__svc_recently_played
    description: "Service layer - Recently played tracks with raw JSON data and deduplication only (like Garmin)"
    columns:
      - name: play_id
        description: "Unique identifier for deduplication (played_at + track_id)"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_spotify__svc_saved_tracks
    description: "Service layer - Saved tracks with raw JSON data and deduplication only (like Garmin)"
    columns:
      - name: saved_track_id
        description: "Unique identifier for deduplication (added_at + track_id)"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_spotify__svc_saved_albums
    description: "Service layer - Saved albums with raw JSON data and deduplication only (like Garmin)"
    columns:
      - name: saved_album_id
        description: "Unique identifier for deduplication (added_at + album_id)"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_spotify__svc_playlists
    description: "Service layer - User playlists with raw JSON data and deduplication only (like Garmin)"
    columns:
      - name: playlist_id
        description: "Spotify playlist ID"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_spotify__svc_top_artists
    description: "Service layer - Top artists with raw JSON data and deduplication only (like Garmin)"
    columns:
      - name: artist_id
        description: "Spotify artist ID"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_spotify__svc_top_tracks
    description: "Service layer - Top tracks with raw JSON data and deduplication only (like Garmin)"
    columns:
      - name: track_id
        description: "Spotify track ID"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
