name: dbt_dataplatform
version: '1.0'
config-version: 2

profile: dbt_dataplatform

model-paths: ["models"]

models:
  dbt_dataplatform:
    lake:
      garmin:
        +materialized: incremental
        +incremental_strategy: merge
        +on_schema_change: sync_all_columns
      +materialized: table
    hub:
      +materialized: view
    product:
      +materialized: view
