name: dbt_dataplatform
version: '1.0'
config-version: 2

profile: dbt_dataplatform

model-paths: ["models"]

models:
  dbt_dataplatform:
    lake:
      +materialized: table
    hub:
      +materialized: view
    product:
      +materialized: view
