name: dbt_dataplatform
version: '1.0'
config-version: 2

profile: dbt_dataplatform

model-paths: ["models"]

models:
  dbt_dataplatform:
    lake:
      garmin:
        +materialized: incremental
        +incremental_strategy: merge
        +on_schema_change: sync_all_columns
        +tags: ["garmin", "lake"]
      spotify:
        +materialized: incremental
        +incremental_strategy: merge
        +on_schema_change: sync_all_columns
        +tags: ["spotify", "lake"]
      +materialized: table
    hub:
      garmin:
        +materialized: view
        +tags: ["garmin", "hub"]
      spotify:
        +materialized: view
        +tags: ["spotify", "hub"]
      +materialized: view
    product:
      daily_recap:
        +materialized: view
        +tags: ["product", "daily_recap"]
      +materialized: view
