name: dbt_dataplatform
version: '1.0'
config-version: 2

profile: dbt_dataplatform

model-paths: ["models"]

models:
  dbt_dataplatform:
    staging:
      +schema: "dp_lake_{{ target.name }}"
    service:
      +schema: "dp_hub_{{ target.name }}"
    product:
      +schema: "dp_product_{{ target.name }}"
    +materialized: view