name: dbt_dataplatform
version: '1.0'
config-version: 2

profile: dbt_dataplatform

model-paths: ["models"]

models:
  dbt_dataplatform:
    lake:
      staging:
        +schema: lake_{{ target.name }}
        +materialized: view
      service:
        +schema: lake_{{ target.name }}
        +materialized: incremental
    hub:
      staging:
        +schema: hub_{{ target.name }}
        +materialized: view
      service:
        +schema: hub_{{ target.name }}
        +materialized: incremental
    product:
      data4:
        +schema: product_{{ target.name }}
        +materialized: view
      homepage:
        +schema: product_{{ target.name }}
        +materialized: view
      classement:
        +schema: product_{{ target.name }}
        +materialized: view