dbt_dataplatform:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: polar-scene-465223-f7
      schema: dp  # Valeur placeholder
      location: US
      threads: 2
      keyfile: ../../gcs_key.json

    prd:
      type: bigquery
      method: service-account
      project: polar-scene-465223-f7
      schema: dp
      location: US
      threads: 2
      keyfile: ../../gcs_key.json
