dbt_dataplatform:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: polar-scene-465223-f7
      dataset: dp
      location: US
      threads: 2

    prd:
      type: bigquery
      method: oauth
      project: polar-scene-465223-f7
      dataset: dp
      location: US
      threads: 4
