dbt_dataplatform:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: polar-scene-465223-f7
      dataset: dp
      location: US
      threads: 2
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '/Users/etienne/MyAll/DEV/ELA_DP/gcs_key.json') }}"

    prd:
      type: bigquery
      method: service-account
      project: polar-scene-465223-f7
      dataset: dp
      location: US
      threads: 2
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '/Users/etienne/MyAll/DEV/ELA_DP/gcs_key.json') }}"
