repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        types: [python]
# Note: Ensure your virtualenv is activated and pre-commit is installed in it for hooks to work properly.
