repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        types: [python]
  - repo: local
    hooks:
      - id: run-unit-tests
        name: Run unit tests
        entry: python3 -m unittest discover -s tests/connectors
        language: system
        pass_filenames: false
        always_run: true
# Note: Ensure your virtualenv is activated and pre-commit is installed in it for hooks to work properly.
