version: 2

sources:
  - name: garmin
    database: polar-scene-465223-f7
    schema: "{{ 'dp_lake_' ~ target.name }}"
    tables:
      - name: normalized__activities
      - name: normalized__activity_details
      - name: normalized__activity_hr_zones
      - name: normalized__activity_splits
      - name: normalized__activity_weather
      - name: normalized__body_battery
      - name: normalized__endurance_score 
      - name: normalized__floors
      - name: normalized__heart_rate
      - name: normalized__hill_score
      - name: normalized__hrv
      - name: normalized_race_predictions
      - name: normalized__sleep
      - name: normalized__stress
      - name: normalized__steps
      - name: normalized__training_status
      - name: normalized__weight
        