version: 2

sources:
  - name: garmin
    database: polar-scene-465223-f7
    schema: "{{ 'dp_lake_' ~ target.name }}"
    tables:
      - name: lake_garmin__stg_garmin_raw
        description: "Universal Garmin raw data table storing all data types as JSON"
        columns:
          - name: raw_data
            description: "Complete original record as JSON from Garmin Connect API"
          - name: data_type
            description: "Type of Garmin data (activities, sleep, steps, body_battery, etc.)"
          - name: dp_inserted_at
            description: "Timestamp when record was ingested into data platform"
          - name: source_file
            description: "Original JSONL filename from connector"

models:
  - name: lake_garmin__svc_activities
    description: "Service layer - Garmin activities with raw JSON data and deduplication only"
    columns:
      - name: activity_id
        description: "Unique identifier for the activity"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_garmin__svc_body_battery
    description: "Service layer - Garmin body battery with raw JSON data and deduplication only"
    columns:
      - name: body_battery_id
        description: "Unique identifier for body battery record"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_garmin__svc_device_info
    description: "Service layer - Garmin device info with raw JSON data and deduplication only"
    columns:
      - name: device_id
        description: "Unique device identifier"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_garmin__svc_floors
    description: "Service layer - Garmin floors data with raw JSON data and deduplication only"
    columns:
      - name: floors_id
        description: "Unique identifier for floors record"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_garmin__svc_heart_rate
    description: "Service layer - Garmin heart rate with raw JSON data and deduplication only"
    columns:
      - name: heart_rate_id
        description: "Unique identifier for heart rate record"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_garmin__svc_hrv
    description: "Service layer - Garmin HRV with raw JSON data and deduplication only"
    columns:
      - name: hrv_id
        description: "Unique identifier for HRV record"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_garmin__svc_race_predictions
    description: "Service layer - Garmin race predictions with raw JSON data and deduplication only"
    columns:
      - name: race_prediction_id
        description: "Unique identifier for race prediction record"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_garmin__svc_sleep
    description: "Service layer - Garmin sleep with raw JSON data and deduplication only"
    columns:
      - name: sleep_id
        description: "Unique identifier for sleep record"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_garmin__svc_steps
    description: "Service layer - Garmin steps with raw JSON data and deduplication only"
    columns:
      - name: steps_id
        description: "Unique identifier for steps record"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_garmin__svc_stress
    description: "Service layer - Garmin stress with raw JSON data and deduplication only"
    columns:
      - name: stress_id
        description: "Unique identifier for stress record"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_garmin__svc_training_status
    description: "Service layer - Garmin training status with raw JSON data and deduplication only"
    columns:
      - name: training_status_id
        description: "Unique identifier for training status record"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"
        
  - name: lake_garmin__svc_weight
    description: "Service layer - Garmin weight with raw JSON data and deduplication only"
    columns:
      - name: weight_id
        description: "Unique identifier for weight record"
      - name: raw_data
        description: "Complete original record as JSON"
      - name: data_type
        description: "Data type identifier"