version: 2

models:
  - name: pct_garmin__activities_spotify_tracks
    description: "Vue produit qui rassemble chaque activité Garmin et la liste ordonnée des écoutes Spotify survenant pendant cette activité. Une ligne par activité."
    columns:
      - name: activity_id
        description: "Identifiant unique de l'activité Garmin."
        tests:
          - not_null
      - name: activity_name
        description: "Nom de l'activité tel que fourni par Garmin."
      - name: activity_type_key
        description: "Type d'activité (run, bike, etc.) selon Garmin."
      - name: activity_type_id
        description: "Identifiant numérique du type d'activité."
      - name: activity_date_utc
        description: "Date de l'activité en UTC."
      - name: activity_date_local
        description: "Date de l'activité selon le fuseau local."
      - name: start_time_gmt
        description: "Timestamp de début en GMT."
        tests:
          - not_null
      - name: end_time_gmt
        description: "Timestamp de fin en GMT, recalculé si absent dans la source."
      - name: start_time_local
        description: "Timestamp de début en heure locale."
      - name: tracks_played_count
        description: "Nombre total de pistes Spotify écoutées pendant l'activité."
      - name: tracks_total_duration_ms
        description: "Somme des durées réellement écoutées (en millisecondes) des pistes pendant l'activité."
      - name: played_tracks
        description: "Array de STRUCT contenant le détail des pistes (identifiants, horaires prévus/réels, durées écoutées, artistes, album, contexte Spotify)."
