version: 2

models:
  - name: product_garmin__daily_summary
    description: Daily summary of all Garmin health and fitness metrics for frontend dashboards
    columns:
      - name: summary_date
        description: Date of the summary (one row per day)
        tests:
          - unique
          - not_null
      - name: sleep_duration_hours
        description: Total sleep time in hours
      - name: sleep_efficiency_percent
        description: Sleep efficiency percentage
      - name: overall_sleep_score
        description: Overall sleep quality score from Garmin
      - name: bedtime_hour
        description: Hour when went to bed (24-hour format)
      - name: waketime_hour
        description: Hour when woke up (24-hour format)
      - name: activity_count
        description: Number of recorded activities on this day
      - name: total_distance_km
        description: Total distance covered in all activities (kilometers)
      - name: total_activity_hours
        description: Total time spent in activities (hours)
      - name: total_calories
        description: Total calories burned in activities
      - name: avg_heart_rate
        description: Average heart rate across all activities
      - name: total_steps
        description: Total steps taken during the day
      - name: avg_weight_kg
        description: Average weight measurement for the day (kg)
      - name: avg_bmi
        description: Average BMI for the day
      - name: avg_body_fat_percent
        description: Average body fat percentage for the day
      - name: has_activity_data
        description: Flag indicating if any activity data exists for this day
      - name: has_sleep_data
        description: Flag indicating if sleep data exists for this day
      - name: has_steps_data
        description: Flag indicating if steps data exists for this day
      - name: has_weight_data
        description: Flag indicating if weight data exists for this day
      - name: has_withings_data
        description: Flag indicating if weight data came from Withings sync
      - name: day_of_week
        description: Day of week (1=Sunday, 7=Saturday)
      - name: day_name
        description: Name of the day (Monday, Tuesday, etc.)
      - name: week_start_date
        description: Start date of the week (Monday)
      - name: month_start_date
        description: Start date of the month

  - name: product_garmin__weekly_summary
    description: Weekly aggregation of Garmin health and fitness metrics for trend analysis
    columns:
      - name: week_start_date
        description: Start date of the week (Monday)
        tests:
          - unique
          - not_null
      - name: week_label
        description: Human-readable week label (e.g., "Jan 15 - Jan 21")
      - name: avg_sleep_duration_hours
        description: Average sleep duration for the week (hours)
      - name: avg_sleep_efficiency_percent
        description: Average sleep efficiency for the week
      - name: avg_sleep_score
        description: Average sleep score for the week
      - name: days_with_sleep_data
        description: Number of days with sleep data in the week
      - name: total_activities
        description: Total number of activities in the week
      - name: total_distance_km
        description: Total distance covered in the week (kilometers)
      - name: total_activity_hours
        description: Total activity time for the week (hours)
      - name: total_calories
        description: Total calories burned in activities for the week
      - name: days_with_activities
        description: Number of days with at least one activity
      - name: total_steps
        description: Total steps for the week
      - name: avg_daily_steps
        description: Average daily steps for the week
      - name: days_with_steps_data
        description: Number of days with steps data in the week
      - name: avg_weight_kg
        description: Average weight for the week (kg)
      - name: days_with_weight_data
        description: Number of days with weight measurements
      - name: met_weekly_steps_goal
        description: Flag indicating if weekly steps goal was met (70k+ steps)
      - name: met_weekly_activity_goal
        description: Flag indicating if weekly activity goal was met (3+ activities)
      - name: met_weekly_sleep_goal
        description: Flag indicating if weekly sleep goal was met (7.5h+ average)
      - name: days_in_week
        description: Number of days included in the week summary
      - name: sleep_data_completeness_percent
        description: Percentage of days with sleep data
      - name: steps_data_completeness_percent
        description: Percentage of days with steps data