version: 2

models:
  - name: hub_chess__player_stats
    description: "Chess.com player statistics across different game modes"
    columns:
      - name: username
        description: "Chess.com username (unique identifier)"
        tests:
          - not_null
          - unique
      - name: rapid
        description: "Chess rapid statistics (rating, record, best performance)"
      - name: blitz
        description: "Chess blitz statistics (rating, record, best performance)"
      - name: bullet
        description: "Chess bullet statistics (rating, record, best performance)"
      - name: daily
        description: "Chess daily statistics (rating, record, best performance)"
      - name: puzzles
        description: "Puzzle and tactics statistics"

  - name: hub_chess__games
    description: "Chess.com games with structured player and game information"
    columns:
      - name: game_id
        description: "Unique game identifier"
        tests:
          - not_null
          - unique
      - name: username
        description: "Username this game record belongs to"
        tests:
          - not_null
      - name: game_url
        description: "URL to the game on Chess.com"
      - name: time_class
        description: "Time control class (rapid, blitz, bullet, daily)"
      - name: rules
        description: "Chess variant rules"
      - name: end_time
        description: "Game end timestamp"
      - name: game_info
        description: "Game metadata (PGN, FEN, time control, etc.)"
      - name: white_player
        description: "White player information and result (rating, result, username, uuid)"
      - name: black_player
        description: "Black player information and result (rating, result, username, uuid)"
      - name: tournament_info
        description: "Tournament/match information if applicable"
      - name: user_game_info
        description: "User-specific game analysis (color, result, rating)"