version: 2

models:
  - name: product_spotify__daily_artist_counts
    description: Nombre d'écoutes par artiste et par jour
    columns:
      - name: play_date
        description: Date de lecture
      - name: artist_id
        description: Identifiant de l'artiste
      - name: play_count
        description: Nombre d'écoutes ce jour
  - name: product_spotify__top10_artists
    description: Top 10 artistes les plus écoutés
    columns:
      - name: artist_id
        description: Identifiant de l'artiste
      - name: play_count
        description: Nombre total d'écoutes
      - name: total_play_time_ms
        description: Temps total d'écoute en millisecondes
  - name: product_spotify__top10_tracks
    description: Top 10 titres les plus écoutés
    columns:
      - name: track_id
        description: Identifiant de la piste
      - name: play_count
        description: Nombre total d'écoutes
      - name: total_play_time_ms
        description: Temps total d'écoute en millisecondes
