main:
  steps:
    - log_start:
        call: sys.log
        args:
          text: "🔥 Spotify hot workflow - recently played"
          severity: INFO
    
    # Fetch recently played
    - fetch_recently_played:
        call: googleapis.run.v2.projects.locations.jobs.run
        args:
          name: projects/polar-scene-465223-f7/locations/europe-west1/jobs/spotify-recently-played
        result: fetch_result
    
    - log_fetch_complete:
        call: sys.log
        args:
          text: ${"✅ Fetch completed - " + fetch_result.name}
          severity: INFO
    
    # Ingest to BigQuery
    - ingest_spotify:
        call: googleapis.run.v2.projects.locations.jobs.run
        args:
          name: projects/polar-scene-465223-f7/locations/europe-west1/jobs/spotify-ingest
        result: ingest_result
    
    - log_ingest_complete:
        call: sys.log
        args:
          text: ${"✅ Ingest completed - " + ingest_result.name}
          severity: INFO
    
    # Run dbt transformations
    - run_dbt:
        call: googleapis.run.v2.projects.locations.jobs.run
        args:
          name: projects/polar-scene-465223-f7/locations/europe-west1/jobs/dbt-run-spotify
        result: dbt_result
    
    - log_dbt_complete:
        call: sys.log
        args:
          text: ${"✅ dbt completed - " + dbt_result.name}
          severity: INFO
    
    # Success
    - return_success:
        return:
          status: "SUCCESS"
          message: "🔥 Spotify hot workflow completed"
          timestamp: ${sys.now()}
          executions:
            fetch: ${fetch_result.name}
            ingest: ${ingest_result.name}
            dbt: ${dbt_result.name}
