{{
  config(
      tags=['garmin', 'lake']
  )
}}

SELECT
    USERPROFILEPK,
    `date`,
    STARTTIMESTAMPGMT,
    ENDTIMESTAMPGMT,
    STARTTIMESTAMPLOCAL,
    ENDTIMESTAMPLOCAL,
    SLEEPSTARTTIMESTAMPGMT,
    SLEEPENDTIMESTAMPGMT,
    SLEEPSTARTTIMESTAMPLOCAL,
    SLEEPENDTIMESTAMPLOCAL,
    HRVSUMMARY,
    HRVREADINGS,
    DP_INSERTED_AT
FROM {{ source('garmin','hrv') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY date ORDER BY dp_inserted_at DESC) = 1