{{
  config(
      tags=['garmin', 'lake']
  )
}}

SELECT
    USERPROFILEPK,
    CALENDARDATE,
    STARTTIMESTAMPGMT,
    ENDTIMESTAMPGMT,
    STARTTIMESTAMPLOCAL,
    ENDTIMESTAMPLOCAL,
    MAXSTRESSLEVEL,
    AVGSTRESSLEVEL,
    STRESSCHARTVALUEOFFSET,
    STRESSCHARTYAXISORIGIN,
    STRESSVALUES,
    BODYBATTERYVALUES,
    DP_INSERTED_AT
FROM {{ source('garmin','stress') }}
QUALIFY
    ROW_NUMBER() OVER (PARTITION BY calendardate ORDER BY dp_inserted_at DESC)
    = 1

