SELECT
	userProfilePK,
	calendarDate,
	`timestamp`,
	timestampLocal,
	deviceId,
	`level`,
	feedbackLong,
	feedbackShort,
	sleepScoreFactorPercent,
	sleepScoreFactorFeedback,
	recoveryTime,
	recoveryTimeFactorPercent,
	recoveryTimeFactorFeedback,
	acwrFactorPercent,
	acwrFactorFeedback,
	stressHistoryFactorPercent,
	stressHistoryFactorFeedback,
	hrvFactorPercent,
	hrvFactorFeedback,
	sleepHistoryFactorPercent,
	sleepHistoryFactorFeedback,
	validSleep,
	primaryActivityTracker,
	`date`,
	data_type,
	TIMESTAMP(`_dp_inserted_at`) AS _dp_inserted_at,
	`_source_file`,
	sleepScore,
	recoveryTimeChangePhrase,
	score,
	hrvWeeklyAverage,
	acuteLoad,
	inputContext
FROM {{ source('garmin','training_readiness') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY calendarDate, timestamp ORDER BY TIMESTAMP(_dp_inserted_at) DESC) = 1
