{{
  config(
      tags=['garmin', 'lake']
  )
}}

SELECT
    USERPROFILEPK,
    CALENDARDATE,
    `date`,
    STARTTIMESTAMPGMT,
    ENDTIMESTAMPGMT,
    STARTTIMESTAMPLOCAL,
    ENDTIMESTAMPLOCAL,
    MAXHEARTRATE,
    MINHEARTRATE,
    RESTINGHEARTRATE,
    LASTSEVENDAYSAVGRESTINGHEARTRATE,
    HEARTRATEVALUES,
    RAW_DATA,
    DP_INSERTED_AT,
    SOURCE_FILE
FROM {{ source('garmin','heart_rate') }}
QUALIFY
    ROW_NUMBER() OVER (PARTITION BY calendardate ORDER BY dp_inserted_at DESC)
    = 1
