SELECT
    USERID,
    `date`,
    VO2MAX,
    HEATALTITUDEACCLIMATION,
    TRAININGSTATUS,
    LOADBALANCE,
    RECORDEDDEVICES,
    RECORDEDDEVICESLOADBALANCE,
    LASTPRIMARYSYNCDATE,
    SHOWSELECTOR,
    RAW_DATA,
    DP_INSERTED_AT,
    SOURCE_FILE
FROM {{ source('garmin','training_status') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY date ORDER BY dp_inserted_at DESC) = 1
